
from openai import OpenAI
client = OpenAI()



# Text and prompt. 
Text="""
As Farhad Manjoo relates in his entertaining (but dubious) foray into the market, bitcoin is the brainchild of a person (or persons) called Satoshi Nakamoto. Computer users can “mine” bitcoins by instructing their computers to solve complex problems generated by the bitcoin network. As more bitcoins are produced, the problems become more complex, requiring more computer power to solve them, and this limits the total number of bitcoins that can be created over time. Bitcoins are themselves simply strings of numbers. Once you own a bitcoin, you can transfer it to someone else (as a gift or to purchase goods) over the Internet. You can also convert it into dollars or other currencies on various exchanges. The Bitcoin network keeps track of where the bitcoins are located, so you cannot spend a single bitcoin over and over again by trying to transmit the identical code."""
prompt="""
summerise the text in {Text}."""

messages = [
    {"role": "user", "content": Text},
    {"role": "user", "content": prompt}
]



# Processing by openai.
# Chat Completions response format:https://platform.openai.com/docs/guides/chat-completions/response-format
response=client.chat.completions.create(
  model="gpt-3.5-turbo-0125",
  messages=messages
)
result = response.choices[0].message.content



# save result and open the txt file automatically.
import os
file_path = r'C:\Users\vhxb\Desktop\output.txt'
with open(file_path, 'w', encoding='utf-8') as file:
    file.write(result)
os.startfile(file_path)
